### PR TITLE
Add GitPod as an online idea

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by JohnNiang** [comment]
Thanks for your idea. That would be better if we had a link target to gitpod  in `README.md`.

**Comment by LinuxSuRen** [comment]
> Thanks for your idea. That would be better if we had a link target to gitpod in `README.md`.

Done.

**Comment by JohnNiang** [comment]
> > Thanks for your idea. That would be better if we had a link target to gitpod in `README.md`.
> 
> Done.

That's great!

**Pull request merged**
